spring:
  application:
    name: Telegram Clone
  datasource:
    driver-class-name: org.postgresql.Driver
  cache:
    type: redis
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

jwt:
  accessTokenExpirationMs: ${JWT_ACCESS_EXPIRATION:900000}     # 15 minutes
  refreshTokenExpirationMs: ${JWT_REFRESH_EXPIRATION:604800000} # 7 days

