app:
  frontend-url: ${FRONTEND_URL:http://localhost:5173}

spring:
  application:
    name: Telegram Clone
  datasource:
    driver-class-name: org.postgresql.Driver
  cache:
    type: redis
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  accessTokenExpirationMs: ${JWT_ACCESS_EXPIRATION:900000}     # 15 minutes
  refreshTokenExpirationMs: ${JWT_REFRESH_EXPIRATION:604800000} # 7 days
